services:
  algorithm:
    build: .
    volumes:
      - ./_data/inputs:/data/inputs:ro
      - ./_data/ddos:/data/ddos:ro
      - ./_data/outputs:/data/outputs:rw
      - ./_data/logs:/data/logs:rw
      - ./algorithm/src:/algorithm/src/
      - ./algorithm/tests:/algorithm/tests/
    env_file:
      - ./.env
    #entrypoint: [ "pytest" ]
